### ISSUE TITLE
Precaución en caso de no poner bien la carpeta de invalid-cases

### ISSUE THREAD

**Issue by jose-tapia** [frcepeda/omegaUp-deploy#51]
Por error puse la carpeta de "invalid-cases" en la raíz del problema y no me marcó error, me dí cuenta después de haber hecho merge en master

Podríamos crear un warning en caso de que la carpeta no se encuentre en `test/`; si la intención no es poner invalid-cases, en dado caso que se dejé vacía la carpeta

**Comment by frcepeda** [comment]
#55
