### ISSUE TITLE
[Lenguajes soportados] Problemas enviados con el deploy no soportan C++20

### ISSUE THREAD

**Issue by jose-tapia** [frcepeda/omegaUp-deploy#56]
Intenté enviar una solución por omegaUp ephemeral y no lo aceptó porque el problema no soporta C++20,

En settings pusimos ["languages: all"](https://github.com/omegaup/OFMI-2022-Selectivo/blob/main/saltos-de-rana/settings.json#L29), pero no incluye el C++20 que es el único C++ que tiene el ephemeral por el momento

cc: @frcepeda

**Comment by frcepeda** [comment]
1c6b36e6e316d3be7d126bbd0a2f172c9e84b32c
